### ISSUE TITLE
oauth/login/google returns 404

### ISSUE THREAD

**Issue by bavobbr** [micronaut-guides/micronaut-oauth2-oidc-google#3]
When following the exact demo (or clone the repo) the URL that should direct to Google just returns a message:

`{
"message": "Page Not Found",
"_links": {
"self": {
"href": "/oauth/login/google",
"templated": false
}
}
}`

Although I followed the guide exactly, exported two vars. 
Not 4, as I dont know what is meant by 

> "You will need to setup OAUTH_CLIENT_ID, OAUTH_CLIENT_SECRET, OIDC_ISSUER_DOMAIN >and OIDC_ISSUER_AUTHSERVERID environment variables.
>
>export OAUTH_CLIENT_ID=XXXXXXXXXX
>export OAUTH_CLIENT_SECRET=YYYYYYYYYY)

What controller handles this URL? Why is it not acting?

**Comment by sdelamo** [comment]
> Although I followed the guide exactly, exported two vars.
> Not 4, as I dont know what is meant by

> "You will need to setup OAUTH_CLIENT_ID, OAUTH_CLIENT_SECRET, OIDC_ISSUER_DOMAIN >and OIDC_ISSUER_AUTHSERVERID environment variables.

> export OAUTH_CLIENT_ID=XXXXXXXXXX
> export OAUTH_CLIENT_SECRET=YYYYYYYYYY)

Yes, only two for this guides. I have updated the guide. 

You maybe getting 404 when accesing `/oauth/login/google` because you did not use google as your client name. 

The next configuration sets a route `/oauth/login/google`

```
micronaut:
  security:
    oauth2:
      clients:
        google:
```

The next configuration sets a route `/oauth/login/mandalorian`

```
micronaut:
  security:
    oauth2:
      clients:
        mandalorian:
```

Routes are registered at `OauthRouteBuilder`
